alter table public.fields
add column if not exists main_crop_name text;

update public.fields
set main_crop_name = crop_names.name
from (
  values
    ('C', 'Citrus'),
    ('C1', 'Grapefruit'),
    ('C2', 'Lemons'),
    ('C3', 'Oranges'),
    ('C4', 'Dates'),
    ('C5', 'Avocados'),
    ('C6', 'Olives'),
    ('C7', 'Miscellaneous Subtropical Fruits'),
    ('C8', 'Kiwis'),
    ('C9', 'Jojoba'),
    ('C10', 'Eucalyptus'),
    ('C11', 'Mixed Subtropical Fruits'),
    ('D', 'Deciduous Fruits and Nuts'),
    ('D1', 'Apples'),
    ('D2', 'Apricots'),
    ('D3', 'Cherries'),
    ('D5', 'Peaches/Nectarines'),
    ('D6', 'Pears'),
    ('D7', 'Plums'),
    ('D8', 'Prunes'),
    ('D9', 'Figs'),
    ('D10', 'Miscellaneous Deciduous'),
    ('D11', 'Mixed Deciduous'),
    ('D12', 'Almonds'),
    ('D13', 'Walnuts'),
    ('D14', 'Pistachios'),
    ('D15', 'Pomegranates'),
    ('D17', 'Pecans'),
    ('F', 'Field Crops'),
    ('F1', 'Cotton'),
    ('F2', 'Safflower'),
    ('F3', 'Flax'),
    ('F4', 'Hops'),
    ('F5', 'Sugar beets'),
    ('F6', 'Corn (field & sweet)'),
    ('F7', 'Grain sorghum'),
    ('F8', 'Sudan'),
    ('F9', 'Castor beans'),
    ('F10', 'Beans (Dry)'),
    ('F11', 'Miscellaneous Field Crops'),
    ('F12', 'Sunflowers'),
    ('F13', 'Hybrid sorghum/sudan'),
    ('F14', 'Millet'),
    ('F15', 'Sugar cane'),
    ('F16', 'Corn, Sorghum and Sudan'),
    ('G', 'Grain and Hay Crops'),
    ('G1', 'Barley'),
    ('G2', 'Wheat'),
    ('G3', 'Oats'),
    ('G6', 'Miscellaneous Grain and Hay'),
    ('G7', 'Mixed Grain and Hay'),
    ('I', 'Idle'),
    ('I1', 'Idle - Short Term'),
    ('I4', 'Idle - Long Term'),
    ('P', 'Pasture'),
    ('P1', 'Alfalfa & Alfalfa Mixtures'),
    ('P2', 'Clover'),
    ('P3', 'Mixed Pasture'),
    ('P4', 'Native Pasture'),
    ('P5', 'Induced high water table native pasture'),
    ('P6', 'Miscellaneous Grasses'),
    ('P7', 'Turf Farms'),
    ('P8', 'Bermuda Grass'),
    ('P9', 'Rye Grass'),
    ('P10', 'Klein Grass'),
    ('R', 'Rice'),
    ('R1', 'Rice'),
    ('R2', 'Wild Rice'),
    ('T', 'Truck, Nursery, and Berry Crops'),
    ('T1', 'Artichokes'),
    ('T2', 'Asparagus'),
    ('T3', 'Beans (green)'),
    ('T4', 'Cole Crops'),
    ('T6', 'Carrots'),
    ('T7', 'Celery'),
    ('T8', 'Lettuce (all types)'),
    ('T9', 'Melons, Squash and Cucumbers'),
    ('T10', 'Onions and Garlic'),
    ('T11', 'Peas'),
    ('T12', 'Potatoes'),
    ('T13', 'Sweet Potatoes'),
    ('T14', 'Spinach'),
    ('T15', 'Tomatoes (processing)'),
    ('T16', 'Flowers, Nursery and Christmas Tree Farms'),
    ('T17', 'Mixed truck (four or more)'),
    ('T18', 'Miscellaneous Truck Crops'),
    ('T19', 'Bush Berries'),
    ('T20', 'Strawberries'),
    ('T21', 'Peppers'),
    ('T22', 'Broccoli'),
    ('T23', 'Cabbage'),
    ('T24', 'Cauliflower'),
    ('T25', 'Brussels sprouts'),
    ('T26', 'Tomatoes (market)'),
    ('T27', 'Greenhouse'),
    ('T28', 'Blueberries'),
    ('T29', 'Asian leafy vegetables'),
    ('T30', 'Lettuce/Leafy Greens'),
    ('T32', 'Tomatoes'),
    ('U', 'Urban'),
    ('UL2', 'Urban Land'),
    ('V', 'Vineyards'),
    ('X', 'Unclassified Fallow'),
    ('YP', 'Young Perennials')
) as crop_names(code, name)
where upper(trim(public.fields.main_crop)) = crop_names.code;

comment on column public.fields.main_crop_name is
  'Human-readable crop name decoded from the main_crop code.';
